### ISSUE TITLE
What does `duration: 2000` mean in the code block?

### ISSUE THREAD

**Issue by dkobak** [bmschmidt/pubmed-explorer#38]
The second slide has the following code block:
```
duration: 2000
```
And the third one:
```
max_points: 750_000
duration: 2000
encoding:
  jitter_radius: null
  jitter_speed: null
```

In both cases my understanding is that the visualization remains the same as in the 1st slide. So why do we need these code blocks at all, and what does `duration` and `jitter_radius:null` do?

Maybe `duration` is the length of the transition animation? But in this case there are no transitions between slides 1/2/3, so can we just delete those two code blocks?
